name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "1 */0 * * *"  # Executa a cada 12 horas, nos minutos 0
  workflow_dispatch:        # Permite execução manual
  push:
    branches:
      - main                # Executa quando houver push na branch main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Swyann             # Seu nome de usuário GitHub
          color: yellow                        # Cor do Pac-Man (opcional)
          speed: 1.5                           # Velocidade da animação (opcional)

      - name: Push SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output                # Branch onde o SVG será publicado
          build_dir: dist                      # Pasta de saída com o SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
